name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask flask-sqlalchemy flask-bcrypt flask-jwt-extended pytest python-dotenv bandit

    - name: Run tests
      run: |
        pytest

    - name: Security check with Bandit
      run: |
        bandit -r .

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server
      run: |
        echo "Deployment step (add your deployment logic here)"